공백 문제 발생
pjok1122/Algorithm-Study pull request #3
Opened 2019-10-29 03:27 UTC by LEEHANI

import sys
input = sys.stdin.readline
위에 코드를 추가했더니 2번째 input()인 boom = input()에서 공백이 발생합니다..
boom = " b4" 말고 boom = "b4"로 입력받고 싶어서 strip()을 썼지만 해결이 안됩니다.. 어떻게 해야하나요?

import를 제거하면 시간초과 발생 ㅠㅠ

2019-10-29 04:00 UTC, pjok1122 commented on _9935_문자열폭발.py
> +boom.strip()  # not working
리스트의 메서드는 return 값 없이 자신을 변화시키는 내용이 많습니다.
예를 들어, list.append(), list.remove(), list.sort() 모두 return 값 없이 자신의 값을 변화시킵니다.

문자열도 리스트의 메서드를 거의 그대로 사용할 수 있지만, 문자열은 자체적으로 값을 변화 시킬 수가 없습니다.
따라서 거의 대부분의 메써드가 값을 반환한다고 기억하시면 됩니다.
즉, boom.strip()의 경우에도 리턴값이 존재하기 때문에 다음과 같이 코드를 수정하시면 됩니다.

boom = boom.strip()

2019-10-29 04:00 UTC, pjok1122 reviewed
수정사항 작성해드렸습니다.

2019-10-29 05:27 UTC, LEEHANI commented on _9935_문자열폭발.py
> +boom.strip()  # not working
그렇군요 ! 근데 boom = boom.strip()로도 해봤었는데 똑같았어요 ...

2019-10-31 04:40 UTC, pjok1122 requested changes
문제를 풀다 포기하셨길래 힌트 보내드립니다.
이름은 스택으로 지었지만, 사실은 스택의 성질이 아니라, 파이썬의 리스트를 활용한 풀이입니다.

2019-10-31 04:40 UTC, pjok1122 commented on _9935_문자열폭발.py
> +        break
현재 이 코드의 시간복잡도는 O(N^2) 이기 때문에 문제가 해결이 안되는 걸로 보입니다.
이 문제를 스택으로 해결해야 한다는 것은 스스로 파악하신 것 같고, 어떻게 하면 효율적으 구현할 수 있는지를 말씀드리겠습니다.

`stack=[]` 이라는 배열을 하나 만들어두고,
`for char in s:
   stack.append(char)`
로 스택에 차곡차곡 쌓아줍니다. 단, 쌓은 후에 맨 끝에 있는 문자열이 'boom'과 동일한지를 파악해야 합니다.
이를 검사하는 방법도 파이썬은 매우 간단합니다.
`boom = list(input())` 로 boom을 리스트 타입으로 바꿔 둔 후,
`if stack[-len(boom):] == boom: ` 이처럼 비교하면 됩니다.

위 코드의 의미는, 뒤에서부터 boom의 길이만큼만 데이터를 뽑아봤을 때, boom과 데이터가 일치한다면! 이라는 뜻입니다.
이 경우에 해당하는 경우에는,
`stack.pop(-1)`을 boom의 길이만큼 반복해주면 됩니다.

최종 결과물은 stack에 저장되어있는데, 이는 list 타입입니다.
따라서 최종 결과물을 string 타입으로 변환해야 하는데, string 타입으로 변환하는 방법은 'join' 이라는 string 객체에 내장된 메써드를 사용합니다.

`print(''.join(stack))` 을 사용해서 출력하면 되고, 만약 스택이 비어있다면 'FRULA'를 출력하세요.

2019-12-24 05:10 UTC, closed without merging